### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#114]
## Problem

The docs website and the Readme contains overlapping information.

## Solution

 To prevent mismatches, let's separate the content of docs and Readme:

1. [Docs](https://hyperjumptech.github.io/monika/overview) should contain guides for users.
2. Readme should contain guides for developers who want to develop Monika.

## TODO

- [x] Remove Getting Started from Readme
- [x] Remove How it works from Readme
- [x] Remove Run Monika using Docker from Readme
- [x] Add a section that tells users to view the Docs for Installation, Quick Start, and How it works.
- [x] Add a section how to develop Monika locally (dependency installation, build, test, formatting, etc.)
