### ISSUE TITLE
Chaining Request

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#82]
To support chaining requests, we need to have a key `requests` inside `probes` that contains an array of request object:

```json
{
  "probes": [
    {
      "id": "1",
      "name": "Example",
      "description": "Probe",
      "interval": 10,
      "requests": [
        {
          "method": "POST",
          "url": "https://example.com/api/login",
          "body": {
            "username": "someusername",
            "password": "somepassword"
          }
        },
        {
          "method": "GET",
          "url": "https://example.com/api/users",
          "headers": {
            "Authorization": "Bearer {{ responses.[0].data.jwt }}"
          }
        },
        {
          "method": "GET",
          "url": "https://example.com/api/users/{{ responses.[1].data.[0].id }}",
          "headers": {
            "Authorization": "Bearer {{ responses.[0].data.jwt }}"
          }
        },
        {
          "method": "GET",
          "url": "{{ responses.[2].config.baseURL }}images/profile/{{ responses.[1].data.[0].id }}.jpg",
          "headers": {
            "Authorization": "Bearer {{ responses.[0].data.jwt }}"
          }
        }
      ]
    }
  ]
}
```

To make Monika's chaining powerful and flexible, we can use [Handlebars](https://handlebarsjs.com/guide/) as templating language. Every **string** value in the config.json is a handlebar template. For example, in the config.json above, we can compile the string

```
"Bearer {{ responses.[0].data.jwt }}"
```

with an input object as follows

```json
{
  "responses": [
    {
      "data": {
        "jwt": "jsonwebtokenhere"
      }
    }
  ]
}
```

and it will result in the following string

```
Bearer jsonwebtokenhere
```

The `responses` that will be provided as input to the Handlebars compiled template is an array of responses object from axios. In axios documentation, [the response schema](https://github.com/axios/axios#response-schema) is defined as follows:

```
{
  // `data` is the response that was provided by the server
  data: {},

  // `status` is the HTTP status code from the server response
  status: 200,

  // `statusText` is the HTTP status message from the server response
  statusText: 'OK',

  // `headers` the HTTP headers that the server responded with
  // All header names are lower cased and can be accessed using the bracket notation.
  // Example: `response.headers['content-type']`
  headers: {},

  // `config` is the config that was provided to `axios` for the request
  config: {},

  // `request` is the request that generated this response
  // It is the last ClientRequest instance in node.js (in redirects)
  // and an XMLHttpRequest instance in the browser
  request: {}
}
```

So to implement this, we can do it in two stages:

First, make sure Monika can handle multiple requests in a single probe. 

- [x] The requests should be perform one after another. 
- [x] If a request fails (status-not-2xx or response-time-greater-than), the next requests should not be performed.
- [x] Like before, the notifications are only sent when the alert has been triggered more than the `incidentThreshold`.

Second, use Handlebars to compile the strings.

- [ ] Make sure a request can use a piece of data from JSON **response of the previous request**, e.g., `"Bearer {{ responses.[0].data.jwt }}"`.
- [ ] Make sure a request can use a piece of data from the **request of the previous request**, e.g., ` "url": "{{ responses.[2].config.baseURL }}images/profile/`.

**Comment by newm4n** [comment]
Also make sure something like this doable

```javascript
"requests": [
        { ... },
        {
        "method": "GET",
        "url": "https://github.com",
        "timeout": 7000,
        "headers": {
          "Cookie": "{{ responses.[0].headers.SetCookie }}"
        },
        "body": {
          "username": "someusername",
          "password": "somepassword"
        }
      }]
```

to simulate some old-school websites that uses cookie to store http sessions.

**Comment by haricnugraha** [comment]
Hi @amitde69, currently Monika can only pass the previous response body to the next request url and/or request header. The ability to pass into the request body is not implemented yet.
